---
abstract: 'a more sensible way to change directories'
author:
  - 'David A Golden <dagolden@cpan.org>'
  - 'Michael G Schwern <schwern@pobox.com> (original author)'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300025, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-chdir
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  File::chdir:
    file: lib/File/chdir.pm
    version: 0.1008
  File::chdir::ARRAY:
    file: lib/File/chdir.pm
    version: 0.1008
  File::chdir::SCALAR:
    file: lib/File/chdir.pm
    version: 0.1008
requires:
  Carp: 0
  Cwd: 3.16
  Exporter: 0
  File::Spec::Functions: 3.27
  perl: 5.006
  strict: 0
  vars: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=File-chdir
  homepage: https://metacpan.org/release/File-chdir
  repository: git://github.com/dagolden/file-chdir.git
version: 0.1008
